import React from "react";

export const StyleSheet = {
  gray: "var(--gray)",
  gray2: "var(--gray-2)",
  gray3: "var(--gray-3)",
  gray4: "var(--gray-4)",
  blue: "var(--blue)",
  blue2: "var(--blue-2)",
  purple: "var(--purple)",
  purple2: "var(--purple-2)",
  white: "var(--white)",
  darkBlue: "var(--dark-blue)",
  darkBlue2: "var(--dark-blue-2)",
  darlBlue3: "var(--dark-blue-3)",
  orange: "var(--orange)",
  orange2: "var(--orange-2)",
  lightBlue: "var(--light-blue)",
  lightBlue2: "var(--light-blue-2)",
  red: "var(--red)",
  lineColor: "var(--line-color)",
  borderRadius: "var(--border-radius)",
  h1: "var(--h1)",
  h2: "var(--h2)",
  h3: "var(--h3)",
  h4: "var(--h4)",
  textBody: "var(--text-body)",
  textBody2: "var(--text-body-2)",
  textBody3: "var(--text-body-3)",
  regular: "var(--regular)",
  semiBold: "var(--semi-bold)",
  bold: "var(--bold)",
  withoutBackground: "var(--without-background)",
  flexStart: "var(--flex-start)",
  flexEnd: "var(--flex-end)",
  center: "var(--center)",
  cardPadding: "var(--card-padding)",
  boxShadow: "var(--box-shadow)",
  boxShadow2: "var(--box-shadow-2)",
};
